trigger:
  - staging

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: patch
    value: 0
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

name: $(major).$(minor).$(patch)-$(Rev:r)

stages:
  - stage: assemble
    displayName: Assemble
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK 5.0'
            inputs:
              packageType: sdk
              version: 5.0.x
          - task: DotNetCoreCLI@2
            displayName: dotnet restore
            inputs:
              command: restore
          - task: DotNetCoreCLI@2
            displayName: dotnet build
            inputs:
              command: build
              arguments: --no-restore /p:TreatWarningsAsErrors=True
          - task: DotNetCoreCLI@2
            displayName: dotnet test
            inputs:
              command: test
              arguments: --no-build
  - stage: deploy
    displayName: Deploy
    dependsOn: assemble
    condition:
      not(eq(variables['build.reason'], 'PullRequest'))
    jobs:
      - job: deployToStaging
        displayName: Deploy to Staging
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              command: buildAndPush
              containerRegistry: SteeltoeContainerRegistry
              repository: net-core-tool-service
              tags: |
                $(Build.BuildId)
                latest
          - task: KubernetesManifest@0
            displayName: Deploy to Staging Cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: SteeltoeStagingAKS
              manifests: deploy/kubernetes/manifest.yaml
              containers: steeltoe.azurecr.io/net-core-tool-service:$(Build.BuildId)
              namespace: initializr
